import type { KV } from "./types";

export const CodeDefs: KV = {
  "Purpose_and_Abstraction.Illustration.High": "Highly abstract information mostly as an indication of circuit components within a bigger picture.",
  "Purpose_and_Abstraction.Programming.Raw": "Including fine-grained circuit information",
  "Purpose_and_Abstraction.Presentation.Low": "Medium to low abstraction, typically for communication purposes. With profound background knowledge (e.g., obtained by reading a paper), a programmer can have a good sense of how to build represented contents.",
  "Composition_and_Progression.View.Circuit_in_circuit": "A circuit is laid within a parent circuit.",
  "Composition_and_Progression.View.Grid": "Multiple views are laid out using axes like small multiples.",
  "Composition_and_Progression.View.H_Concat": "Multiple views are horizontally concatenated.",
  "Composition_and_Progression.View.Single_view": "There is only a single view.",
  "Composition_and_Progression.View.Custom": "Using custom composition/layout of views.",
  "Composition_and_Progression.View.Facet": "Multiple views are listed by row and column with no view-level axis.",
  "Composition_and_Progression.View.Overlapped": "Multiple views are overlapped on each other.",
  "Composition_and_Progression.View.Dashboard": "Views are located within a bigger dashboard.",
  "Composition_and_Progression.View.V_Concat": "Multiple views are vertically concatenated.",
  "Composition_and_Progression.Progression.Symbols": "Multiple views are connected using symbols like arrows, equality, etc.",
  "Composition_and_Progression.Progression.Zoom_lens": "Overview and detail views are connected via a zoom lens method.",
  "Layout_and_Format.Layout.Node_edge": "Showing a circuit using nodes and edges.",
  "Layout_and_Format.Layout.Hybrid_multiples": "The use of small multiples to show temporal progression.",
  "Layout_and_Format.Layout.Hybrid_3D": "The use of 3D visualizations to have both qubit locations and time in position encodings.",
  "Layout_and_Format.Layout.Hybrid_animation": "The use of animation to show temporal progression.",
  "Layout_and_Format.Layout.Traditional": "Qubits are vertically positioned, and the time is horizontally positioned (or vice versa).",
  "Layout_and_Format.Layout.On_machine": "Qubits are positioned based on their location on a hardware chip.",
  "Layout_and_Format.Format.Heatmap": "Representing components using heatmap cells.",
  "Layout_and_Format.Format.Circuit": "Representing components as corresponding symbols.",
  "Layout_and_Format.Mode.Text": "Showing visualizations using texts only (for CLI-compliance)",
  "Layout_and_Format.Direction.Horizontal": "Horizontally directed traditional layout.",
  "Layout_and_Format.Direction.Vertical": "Vertically directed traditional layout.",
  "Qubit.Information.Name": "Qubit's name (if they are named by a programmer)",
  "Qubit.Information.Qubit_group_or_type": "A type or group of qubits (e.g., ancilla vs. data qubits)",
  "Qubit.Information.Logical_physical_mapping": "Mapping from logical qubits to physical qubits after circuit optimization.",
  "Qubit.Information.Index": "The index of qubit",
  "Qubit.Information.Fidelity": "The decoherence time and error rate associated with a qubit",
  "Qubit.Information.Qubit": "The location and existence of a qubit",
  "Qubit.Information.N_Qubits": "The number of qubits in a circuit or in a group",
  "Qubit.Information.State": "The state of a qubit (see \"State\" for more details)",
  "Qubit.Information.Spin": "The spin state of a qubit.",
  "Qubit.Representation.Glyph": "Representing qubits as glyphs that allow further encoding(s).",
  "Qubit.Representation.Cell": "Representing qubits as heatmap cells.",
  "Qubit.Representation.Icon": "Representing qubits as icons or symbols (no additional encodings).",
  "Qubit.Representation.Text": "Representing qubits as text (their names, indices, bit lines, etc.)",
  "Qubit.Representation.Bit_line": "Representing qubits as bit lines.",
  "Qubit.Representation.Grid": "Representing qubits as nodes on a grid.",
  "State.Representation.Theory_notation": "Showing qubit states as theoretical notations.",
  "State.Representation.Color": "Showing qubit states as colors.",
  "State.Representation.Bloch_sphere": "Showing qubit states as Bloch spheres or Bloch sphere-inspired representations.",
  "State.Representation_characteristic.Swapping": "Indicating that qubit states are swapped.",
  "State.Representation_characteristic.At_final": "Showing qubit states at the end of a circuit.",
  "State.Representation_characteristic.Selective": "Selectively showing qubit states.",
  "State.Representation_characteristic.Changes_over_moments": "Showing changes to qubit states over moments.",
  "State.Representation_characteristic.At_init": "Showing qubit states at the beginning of a circuit.",
  "Bit_lines.Representation_characteristic.Crossing": "Indicating the crossings of bit lines.",
  "Bit_lines.Representation_characteristic.Quantum_classical_connected": "Quantum and classical bit lines are not connected after gates instead of having separate classical register part.",
  "Bit_lines.Representation_characteristic.Hidden": "Bit lines are hidden.",
  "Bit_lines.Representation_characteristic.Special": "Using some special notations in bit lines.",
  "Bit_lines.Representation_characteristic.Selective": "Selectively showing bit lines.",
  "Bit_lines.Representation_characteristic.Dynamic": "Moving bit lines dynamically.",
  "Bit_lines.Representation_characteristic.Merge_diverge": "Bit lines are merged or diverged.",
  "Bit_lines.Representation_characteristic.Static": "Static bit lines with no dynamicity.",
  "Bit_lines.Representation_characteristic.Grouped": "Bit lines are grouped.",
  "Bit_lines.Representation_characteristic.Quantum_classical_undistinguished": "Quantum and classical bit lines are not distinguished.",
  "Bit_lines.Representation_characteristic.Collapsed": "Bit lines are collapsed mostly for classical register lines.",
  "Qubit_connectivity.Information.Partition": "The partition or grouping of qubit connectivities.",
  "Qubit_connectivity.Information.2_qubit": "Two-qubit connectivity.",
  "Qubit_connectivity.Information.N-Qubit": "N-qubit (mostly 4) connectivity.",
  "Qubit_connectivity.Representation.Hidden": "Qubit connectivity information is hidden.",
  "Qubit_connectivity.Representation.Glyph": "The qubit connectivity itself is represented as glyphs that allow further encoding.",
  "Qubit_connectivity.Representation.Grid_cell": "The qubit connectivity is represented as cells shaped by a grid layout.",
  "Qubit_connectivity.Representation.Grid": "The qubit connectivity is represented as grid lines.",
  "Qubit_connectivity.Representation.Cell": "The qubit connectivity is represented as heatmap cells.",
  "Qubit_connectivity.Representation_characteristic.With_weight": "Weight terms assigned on qubit connectivity.",
  "Qubit_connectivity.Representation_characteristic.Selective": "Selectively showing qubit connectivity information.",
  "Gate.Information.Index": "The index of a gate.",
  "Gate.Information.Parameters": "The parameters of a gate.",
  "Gate.Information.State_preparation": "Initial state preparation as a gate.",
  "Gate.Information.Gate_type": "The type of a gate.",
  "Gate.Information.Pulse": "The pulse data for manipulating a gate.",
  "Gate.Information.Error_rate": "The error rate of a gate.",
  "Gate.Information.Error_type": "The type of an error of a gate.",
  "Gate.Information.Gate_group": "The group of gates.",
  "Gate.Representation.Color": "Showing gate information using colors.",
  "Gate.Representation.Line_chart": "Showing pulse data are using a line chart.",
  "Gate.Representation.Custom": "Using custom notations for gates.",
  "Gate.Representation.Box_and_lines": "Using box and lines for gates.",
  "Gate.Representation.Shape": "Using shapes for different gate types.",
  "Gate.Representation.Traditional": "Using widely known, conventional gate notations.",
  "Gate.Representation.Box_with_letters": "Using box operators with names in it.",
  "Gate.Representation.Text": "Using text for representing gates.",
  "Gate.Representation_characteristic.Grouped": "Gates are grouped.",
  "Gate.Representation_characteristic.Given": "Gates are given, so not explicitly shown.",
  "Gate.Representation_characteristic.Qubit_indication": "For multi-qubit gates, indicating to which qubit a gate applies.",
  "Measure.Information.Expected_value": "The expected outcome from a measurement.",
  "Measure.Information.Named": "The name of a measurement.",
  "Measure.Information.Puali_axis": "The Pauli axis of a measurement.",
  "Measure.Representation.Traditional": "Representing measurements using traditional symbols.",
  "Measure.Representation.Custom_icon": "Representing measurements using custom icons.",
  "Measure.Representation.Next_to_final_gate": "Showing measurement right next to the final gates.",
  "Measure.Representation.Quantum_to_classical": "How measurements are connected to classical processing.",
  "Measure.Representation.Hidden": "Measurements are hidden.",
  "Measure.Representation_characteristic.No_classical": "No classical register is shown.",
  "Measure.Representation_characteristic.Grouped": "Measurements are grouped or merged.",
  "Measure.Representation_characteristic.On_machine_view": "Showing measurements on an on-machine layout.",
  "Measure.Representation_characteristic.Annotated": "Measurements are annotated.",
  "Measure.Representation_characteristic.Quantum_to_classical": "Connecting measurements to the classical register.",
  "Mid_circuit_measure.Information.Back_to_quantum": "Whether mid-circuit measurement outcomes are fed back to the quantum circuit.",
  "Mid_circuit_measure.Information.Between_gates": "Whether mid-circuit measurement outcomes are happening between two gates.",
  "Mid_circuit_measure.Information.Continued": "There are continuing quantum processing after mid-circuit measurement (on those measured qubits).",
  "Mid_circuit_measure.Information.With_classical_component": "Whether mid-circuit measurement outcomes are fed back to the quantum circuit after some classical processing.",
  "Mid_circuit_measure.Representation.Arrow_with_classical_component": "Directing mid-circuit measurements to classical components using arrows.",
  "Mid_circuit_measure.Representation.Double_line": "Using double lines to indicate mid-circuit measurements.",
  "Mid_circuit_measure.Representation.Hit_classical_line": "Sending the measured outcomes to the classical register and fitting them back to quantum parts.",
  "Classical.Information.Memory": "Changes to classical memory.",
  "Classical.Information.Registry": "Classical bit register.",
  "Classical.Representation.Single_line": "Showing the classical register as a single line.",
  "Classical.Representation.Double_line": "Showing the classical register as a double line.",
  "Selection.Unit.Moment": "Selecting the time order of gates.",
  "Selection.Unit.View": "Selecting views.",
  "Selection.Unit.Measure": "Selecting measurements.",
  "Selection.Unit.Quantum_classical": "Distinguishing quantum parts and classical parts.",
  "Selection.Unit.2_qubit_connectivity": "Selecting two-qubit connectivities.",
  "Selection.Unit.Circuit": "Selecting parts of a circuit.",
  "Selection.Unit.Gate": "Selecting gates.",
  "Selection.Unit.N_qubit_connectivity": "Selecting N-qubit connectivities",
  "Selection.Unit.Qubit": "Selecting cubits",
  "Selection.Method.Emphasis": "Showing a selection using emphasis.",
  "Selection.Method.Aggregation": "Showing a selection by aggregating elements.",
  "Selection.Method.Encoding": "Showing a selection using an encoding.",
  "Selection.Method.Annotation": "Showing a selection using an annotation.",
  "Selection.Method.Hover_highlight": "Showing a selection through hover highlighting.",
  "Selection.Method.Spacing": "Showing a selection based on spacing between elements.",
  "Selection.Characteristic.Nested": "Selections are nested.",
  "Selection.Characteristic.Cross_view": "Making selections across views.",
  "Channel.Object.Stroke_width": "Encoding on the stroke width of an object.",
  "Channel.Object.Stroke_color": "Encoding on the stroke color of an object.",
  "Channel.Object.Fill_pattern": "Encoding on the fill pattern of an object.",
  "Channel.Object.Fill_color": "Encoding on the fill color of an object.",
  "Channel.Object.Stroke_dahsed": "Encoding on the stroke dash of an object.",
  "Channel.Object.Shape": "Encoding on the shape of an object.",
  "Channel.Object_shade.Stroke_color": "Encoding on the stroke color of the shade of an object.",
  "Channel.Object_shade.Fill_color": "Encoding on the fill color of the shade of an object.",
  "Channel.Text.Fill_color": "Encoding on the fill color of a text element.",
  "Channel.Text.Text": "Encoding on the text of a text element.",
  "Reference.Axis.Time": "The axis for time progression.",
  "Reference.Axis.Space": "The axis for space.",
  "Reference.Legend.Quantity_error": "The legend for a quantity (error rate).",
  "Reference.Legend.Child_circuit": "The legend for child circuits.",
  "Reference.Legend.Quantity_state": "The legend for a quantity (qubit state).",
  "Reference.Legend.Cateogry_grouping": "The legend for categories (component grouping).",
  "Reference.Legend.Quantity_etc": "The legend for a quantity (etc.).",
  "Reference.Legend.Grid_axis": "The legend for qubit layout.",
  "Reference.Legend.Category_type": "The legend for categories (component type).",
  "Narrative.Title.Sub_view": "The titles of child views.",
  "Narrative.Title.Main_view": "The main title.",
  "Narrative.Title.Indexing": "Indices of views.",
  "Narrative.Annotation.Name_and_index": "Annotating name and index.",
  "Narrative.Annotation.Progression": "Annotating the progression of views.",
  "Narrative.Annotation.Element_details": "Annotation for details about elements",
  "Narrative.Annotation.Program_global_phase": "Annotation for program information (global phase).",
  "Narrative.Annotation.Program_others": "Annotation for other program-related information",
  "Narrative.Annotation.Process": "Annotation for different processes.",
  "Narrative.Annotation.Selection": "Annotation for a selection.",
  "Narrative.Annotation.Program_depth": "Annotation for program information (depth).",
  "Narrative.Annotation.With_emphasis": "Annotation attached to an emphasis.",
  "Narrative.Annotation.Description": "Description for a circuit.",
  "Narrative.Annotation.Program_loop": "Annotation for program information (loop).",
  "Narrative.Emphasis.Element_detail": "Emphasis for details about elements",
  "Narrative.Emphasis.Selection": "Emphasis for a selection.",
  "Narrative.Emphasis.Selection_cross_view": "Emphasis for a selection across views.",
  "Narrative.Emphasis.Selection_between_element": "Emphasis for the relationship between elements.",
  "Narrative.Emphasis.Program_information": "Emphasis for program information.",
  "Narrative.Emphasis.Progression": "Emphasis the progression of views.",
  "Narrative.Attachment.Classical_processing": "Attachment for classical processing.",
  "Narrative.Attachment.Gate_fidelity": "Attachment for detailed gate fidelity.",
  "Narrative.Attachment.Problem_topic": "Attachment for the topic related to a given problem.",
  "Narrative.Attachment.Unitary": "Summarizing a circuit as a unitary matrix.",
  "Narrative.Attachment.Summary_statistics": "Showing some summary statistics for a circuit (e.g., the number of qubits and gates).",
  "Narrative.Attachment.Expected_results": "Showing expected measurement outcomes.",
  "Narrative.Attachment.Classical_processing_optimization": "Attachment for circuit optimization methods.",
  "Management.Data_transform.Filter": "Filtering transformation.",
  "Management.Data_transform.Aggregate": "Aggregate transformation.",
  "Management.Space_management.Spacing": "Compressing the space between elements when they are less important.",
  "Management.Space_management.Pagination": "Sectioning a circuit into multiple pages.",
  "Management.Space_management.Overlapping": "Overlapping multiple elements or views.",
  "Management.Space_management.Slash_line": "Using a slash line over a bit line to show that it is a merge of multiple (qu)bits.",
  "Management.Space_management.Point_to_target_qubit": "Omitting some qubit lines and pointing to omitted qubits of multi-qubit gates.",
  "Management.Space_management.Filter_out": "Filtering out elements and optionally indicating that they are filtered out using ellipsis or equivalent symbols.",
  "Interaction.Exploration.Cross-highlight": "Supporting interactive cross-highlighting between elements. ",
  "Interaction.Exploration.Tooltip": "Showing on-demand details using tooltips.",
  "Interaction.Exploration.Toggling": "Toggling between different information (e.g., shifting error types for an error rate visualizations).",
  "Interaction.Exploration.Aggregation": "Interactively aggregating/disaggregating components.",
  "Interaction.Exploration.Slideshow": "Self-paced interactive slideshow.",
  "Interaction.Exploration.Select": "Interactions for selecting elements (e.g., brushing).",
  "Interaction.Exploration.Filtering": "Filtering in/out components.",
  "Interaction.Composition.Keyboard_shortcut": "Writing a circuit via keyboard shortcuts.",
  "Interaction.Composition.Context_menu": "Writing a circuit via a context menu.",
  "Interaction.Composition.Drag_and_drop": "Writing a circuit via drag-and-drop interaction.",
  "Purpose_and_Abstraction.Illustration": "Highly abstract information mostly as an indication of circuit components within a bigger picture.",
  "Purpose_and_Abstraction.Programming": "Including fine-grained circuit information",
  "Purpose_and_Abstraction.Presentation": "Medium to low abstraction, typically for communication purposes. With profound background knowledge (e.g., obtained by reading a paper), a programmer can have a good sense of how to build represented contents.",
  "Composition_and_Progression.View": "View composition",
  "Composition_and_Progression.Progression": "Multi-view progression",
  "Layout_and_Format.Layout": "The layout for spatial and temporal dimensions.",
  "Layout_and_Format.Format": "The primary representation methods.",
  "Layout_and_Format.Mode": "Text or graphics.",
  "Layout_and_Format.Direction": "The direction of traditional layout.",
  "Qubit.Information": "Qubit-related information to visualize.",
  "Qubit.Representation": "How to display qubit-related information.",
  "State.Representation": "How to display qubit states.",
  "State.Representation_characteristic": "Considerations for showing qubit states.",
  "Bit_lines.Representation_characteristic": "Considerations for showing qubit as bit lines.",
  "Qubit_connectivity.Information": "Qubit connectivity-related information to visualize.",
  "Qubit_connectivity.Representation": "How to display qubit connectivity-related information.",
  "Qubit_connectivity.Representation_characteristic": "Considerations for showing qubit connectivity-related information.",
  "Gate.Information": "Gate-related information to visualize.",
  "Gate.Representation": "How to display gate-related information.",
  "Gate.Representation_characteristic": "Considerations for showing gate-related information.",
  "Measure.Information": "Measurement-related information to visualize.",
  "Measure.Representation": "How to display measurement-related information.",
  "Measure.Representation_characteristic": "Considerations for showing measurement-related information.",
  "Mid_circuit_measure.Information": "Mid-circuit measurement-related information to visualize.",
  "Mid_circuit_measure.Representation": "How to display mid-circuit measurement-related information.",
  "Classical.Information": "Classical processing-related information to show.",
  "Classical.Representation": "How to display classical processing-related information.",
  "Selection.Unit": "Selection units.",
  "Selection.Method": "Representation methods for selections.",
  "Selection.Characteristic": "Considerations for selection representations.",
  "Channel.Object": "Encoding channels for an object.",
  "Channel.Object_shade": "Encoding channels for an object's shade.",
  "Channel.Text": "Encoding channels for a text element.",
  "Reference.Axis": "Axis for time and space.",
  "Reference.Legend": "Legend for quantity and category.",
  "Narrative.Title": "Title.",
  "Narrative.Annotation": "Text annotations.",
  "Narrative.Emphasis": "Visual emphases or embellishments.",
  "Narrative.Attachment": "The use of additional attachments (including non-circuit visualizations).",
  "Management.Data_transform": "Data transformation methods.",
  "Management.Space_management": "Space management methods.",
  "Interaction.Exploration": "Interaction techniques for exploration.",
  "Interaction.Composition": "Interaction techniques for composition.",
  "Purpose_and_Abstraction": "Abstraction level, in relation to purposes.",
  "Composition_and_Progression": "View composition and progression.",
  "Layout_and_Format": "Primary layout and format.",
  "Qubit": "Qubit components.",
  "State": "Qubit information special case: state.",
  "Bit_lines": "Qubit representation special case: bit lines.",
  "Qubit_connectivity": "Qubit connectivity components.",
  "Gate": "Gate components.",
  "Measure": "Measurement components.",
  "Mid_circuit_measure": "Mid-circuit measurement components.",
  "Classical": "Classical processing components.",
  "Selection": "Selection units and methods.",
  "Channel": "Visual channels for additional information.",
  "Reference": "The use of legends and axes.",
  "Narrative": "Narrative elements.",
  "Management": "Data and space management techniques.",
  "Interaction": "Interaction techniques. ",
};

export const LevelOrder: KV[] = [{
  Name: "View",
  Items: [
    "Purpose_and_Abstraction",
    "Composition_and_Progression",
    "Layout_and_Format"]
}, {
  Name: "Component",
  Items: [
    "Qubit",
    "State",
    "Bit_lines",
    "Qubit_connectivity",
    "Gate",
    "Measure",
    "Mid_circuit_measure",
    "Classical"]
}, {
  Name: "Management",
  Items: [
    "Selection",
    "Channel",
    "Reference",
    "Management"
  ]
}, {
  Name: "Narrative",
  Items: ["Narrative"]
}, {
  Name: "Interaction",
  Items: ["Interaction"]
}];